name: Deploy to XREA via SFTP

on:
  push:
    branches:
      - main  # mainブランチにPushされた時に実行
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir -p dist
          cp index.html style.css app.js dist/

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.XREA_HOST }}
          port: ${{ secrets.XREA_PORT }}
          username: ${{ secrets.XREA_USER }}
          password: ${{ secrets.XREA_PASSWORD }}
          local_path: './dist/*'
          remote_path: ${{ vars.FTP_SERVER_DIR || '/public_html/madakotools/nazorigaki' }}
          sftp_only: true
